### PR TITLE
Provides true path validation.

### PR DESCRIPTION
**Pull request by brad-jones**
Related to https://github.com/carlansley/swagger2/pull/19

Obviously I'll leave the package versioning up to yourself but this PR contains the changes required to use swagger2 once https://github.com/carlansley/swagger2/pull/19 has been merged.

### CODE REVIEW

**Comment by carlansley** [comment]
Now that swagger2 has the path validation, this PR can be updated with the new version.

**Comment by brad-jones** [comment]
Not sure if you wanted me to update the PR or not but the new version of swagger2 doesn't actually appear to be published to npm just yet.

**Comment by carlansley** [comment]
Sorry my bad, didn't do the npm publish. Done now.

**Comment by brad-jones** [comment]
PR updated to use swagger2@0.0.26

**Pull request merged**
